# Generated by Django 4.2.10 on 2024-02-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255)),
                ('events', models.BooleanField(default=False)),
                ('event_size', models.PositiveIntegerField(default=0)),
                ('festival', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(choices=[('Meals', 'Meals'), ('Masala Dosa', 'Masala Dosa'), ('Uzhunnu Vada', 'Uzhunnu Vada'), ('Puri Masala', 'Puri Masala'), ('Biriyani', 'Biriyani'), ('Parippu Vada', 'Parippu Vada'), ('Puttum Kadala', 'Puttum Kadala')], max_length=255)),
                ('n_customers', models.PositiveIntegerField(default=0)),
                ('prediction_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='restaurants.predictionrequest')),
            ],
        ),
    ]
