# Generated by Django 4.2.10 on 2024-02-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(choices=[('Meals', 'Meals'), ('Masala Dosa', 'Masala Dosa'), ('Uzhunnu Vada', 'Uzhunnu Vada'), ('Puri Masala', 'Puri Masala'), ('Biriyani', 'Biriyani'), ('Parippu Vada', 'Parippu Vada'), ('Puttum Kadala', 'Puttum Kadala')], max_length=255)),
                ('ingredient', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('l', 'l'), ('units', 'units')], max_length=255)),
            ],
            options={
                'unique_together': {('food_item', 'ingredient')},
            },
        ),
    ]
