# Generated by Django 4.2.10 on 2024-02-17 07:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolingrequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
