# Generated by Django 4.2.10 on 2024-02-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer'),
        ),
    ]
